### ISSUE TITLE
looper pephub error

### ISSUE THREAD

**Issue by nsheff** [pepkit/hello_looper#10]
```
looper run --looper-config looper_pephub.yaml
Looper version: 1.5.2-dev
Command: run
Using default config. No config found in env var: ['DIVCFG']
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 1116, in main
    project_dict=PEPHubClient()._load_raw_pep(
  File "/home/nsheff/.local/lib/python3.8/site-packages/pephubclient/pephubclient.py", line 266, in _load_raw_pep
    correct_proj_dict = ProjectDict(**json.loads(decoded_response))
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for ProjectDict
name
  field required (type=value_error.missing)
_sample_dict
  field required (type=value_error.missing)
```

**Comment by khoroshevskyi** [comment]
Could you please check versions of:
1) looper
2) pephubclient
3) peppy

I have:
1) looper==1.5.2.dev0
2) peppy==0.40.0a3
3) pephubclient ==0.1.2

And everything works for me

**Comment by nsheff** [comment]
Need to update pephubclient in looper reqs.
